name: scan_build

on:
  pull_request:
    types: [labeled]

env:
  PACKAGE_NAME: maliput_py
  ROS_DISTRO: foxy
  ROS_WS: maliput_ws

jobs:
  static_analysis:
    if: contains(github.event.pull_request.labels.*.name, 'do-static-analyzer-test')
    name: Static analysis
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    env:
      LINKER_PATH: /usr/bin/lld-8
    steps:
    # setup-ros first since it installs git, which is needed to fetch all branches from actions/checkout
    - uses: ros-tooling/setup-ros@0.2.1
    - uses: actions/checkout@v2
      with:
        path: ${{ env.ROS_WS }}/src/${{ env.PACKAGE_NAME }}
    - name: clang 8 install
      shell: bash
      run: ${{ env.ROS_WS }}/src/${{ env.PACKAGE_NAME }}/.github/clang_suite_installation.sh
    # clone private dependencies
    - uses: actions/checkout@v2
      with:
        repository: ToyotaResearchInstitute/maliput
        fetch-depth: 0
        path: ${{ env.ROS_WS }}/src/maliput
        token: ${{ secrets.MALIPUT_TOKEN }}
    # clone public dependencies
    - name: vcs import
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      run: vcs import src < src/${PACKAGE_NAME}/.github/dependencies.repos
    - name: check if dependencies have a matching branch
      shell: bash
      working-directory: ${{ env.ROS_WS }}/src
      run: ./${PACKAGE_NAME}/.github/try_vcs_checkout ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} .
    - run: colcon graph
      shell: bash
      working-directory: ${{ env.ROS_WS }}
    - name: rosdep install
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      run: |
        rosdep update --include-eol-distros;
        rosdep install  -i -y --rosdistro ${ROS_DISTRO} --skip-keys "pybind11" --from-paths src
    - name: colcon build up-to
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      run: |
        . /opt/ros/${ROS_DISTRO}/setup.bash;
        colcon build --packages-up-to ${PACKAGE_NAME} \
          --packages-skip ${PACKAGE_NAME} \
          --event-handlers=console_direct+ \
          --cmake-args -DCMAKE_LINKER=${LINKER_PATH}
    - name: scan_build
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      run: |
        . /opt/ros/${ROS_DISTRO}/setup.bash;
        ./src/${PACKAGE_NAME}/.github/run_scan_build \
            --cmake-args -DCMAKE_LINKER=${LINKER_PATH} \
            --packages-select ${PACKAGE_NAME} \
            --event-handlers=console_direct+;
